import { A2uiMessageProcessor } from '@a2ui/lit/0.8';

const root = document.getElementById('root')!;

// A2UI surface JSON — what an AI agent would generate
const surfaceJson = {
  surfaceUpdate: {
    components: [
      { id: "root", component: { Column: { children: { explicitList: ["title", "card"] } } } },
      { id: "title", component: { Text: { text: { literalString: "🤖 A2UI Agent Rendering" }, usageHint: "h1" } } },
      { id: "card", component: {
        Card: { children: { explicitList: ["nameRow", "emailRow", "btnRow", "result"] } }
      }},
      { id: "nameRow", component: {
        Row: { children: { explicitList: ["nameLabel", "nameInput"] } }
      }},
      { id: "nameLabel", component: { Text: { text: { literalString: "Name:" } } } },
      { id: "nameInput", component: {
        TextField: { label: { literalString: "" }, text: { path: "/data/name" } }
      }},
      { id: "emailRow", component: {
        Row: { children: { explicitList: ["emailLabel", "emailInput"] } }
      }},
      { id: "emailLabel", component: { Text: { text: { literalString: "Email:" } } } },
      { id: "emailInput", component: {
        TextField: { label: { literalString: "" }, text: { path: "/data/email" } }
      }},
      { id: "btnRow", component: {
        Row: { children: { explicitList: ["submitBtn"] } }
      }},
      { id: "submitBtn", component: {
        Button: { child: "btnText", action: { name: "submit" } }
      }},
      { id: "btnText", component: { Text: { text: { literalString: "✅ Submit" } } } },
      { id: "result", component: { Text: { text: { path: "/data/result" } } } }
    ]
  }
};

// Process the A2UI surface
const processor = new A2uiMessageProcessor();
processor.processMessages([surfaceJson]);

// Show what was parsed
root.innerHTML = `
  <pre style="background:#1a1a2e;padding:1rem;border-radius:8px;color:#00d4aa;overflow:auto">
✅ A2UI Surface processed successfully!

Components parsed: ${processor.getSurfaces().size} surface(s)
State tree: ${JSON.stringify(processor.getData(), null, 2)}

=== What this means ===
This JSON was generated by an AI agent and describes a full UI:
- Column layout with Card containing form fields
- TextField components bound to /data/name and /data/email
- Button with action "submit"
- All declarative — no imperative code

=== How it works in your app ===
AI agent → A2UI JSON → @a2ui/lit renders native components
Your Tauri/Rust app just needs to:
1. Receive A2UI JSON from AI agent
2. Pass to A2uiMessageProcessor
3. Lit web components auto-render the UI
  </pre>
`;
